### ISSUE TITLE
raspbian roscore

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [PabloGN/Docker-raspbian-ros-indigo#1]
Hello,
I am trying to use `pablogn/rpi-ros-core-indigo:10` image. But I cannot make it work.
I am using the cmd `docker run -it --rm -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static pablogn/rpi-ros-core-indigo:10` to start the container.
When I type `roscore` I get these errors:
```
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 279, in start
    self.runner.launch()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 654, in launch
    self._setup()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 630, in _setup
    self._launch_master()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 394, in _launch_master
    validate_master_launch(m, self.is_core, self.is_rostest)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 83, in validate_master_launch
    if not rosgraph.network.is_local_address(m.get_host()):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 176, in is_local_address
    local_addresses = ['localhost'] + get_local_addresses()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 219, in get_local_addresses
    for iface in netifaces.interfaces():
OSError: [Errno 97] Address family not supported by protocol
```
Any idea?
Thx

**Comment by PabloGN** [comment]
Hi, Guillaume. I cannot replicate the error:
```
$ docker run -it --rm -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static pablogn/rpi-ros-core-indigo:10
Unable to find image 'pablogn/rpi-ros-core-indigo:10' locally
10: Pulling from pablogn/rpi-ros-core-indigo
a3ed95caeb02: Already exists 
ba3827fc661c: Already exists 
2d0175befe79: Already exists 
a9a0626475df: Already exists 
67fcc541d69c: Already exists 
e7b1a08769d2: Already exists 
Digest: sha256:34f5739e71f8c8cec7f318a0bcf4bba56328a27c47383d0447760b83a064f146
Status: Downloaded newer image for pablogn/rpi-ros-core-indigo:10
pi@6b5dc3ee426d:~$ roscore
... logging to /home/pi/.ros/log/29c4e4da-9c54-11e7-a995-0242ac110002/roslaunch-6b5dc3ee426d-32.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://6b5dc3ee426d:44952/
ros_comm version 1.11.19


SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.19

NODES

auto-starting new master
process[master]: started with pid [43]
ROS_MASTER_URI=http://6b5dc3ee426d:11311/

setting /run_id to 29c4e4da-9c54-11e7-a995-0242ac110002
process[rosout-1]: started with pid [56]
started core service [/rosout]
```

Check your network definition, since the error relies on that, related to IP6 as said in https://github.com/jupyterhub/jupyterhub/issues/76
 
```
$ ifconfig 
docker0   Link encap:Ethernet  HWaddr 02:42:d0: 
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:

eth0      Link encap:Ethernet  HWaddr b8:27:eb:
          inet addr:158.227  Bcast:158.227.
          inet6 addr: fe80::ba27:ebff:fe

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host

wlan0     Link encap:Ethernet  HWaddr b8:27:eb
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
```

**Comment by Guillaumebeuzeboc** [comment]
Thanks for the answer.
My `/etc/hosts`  is correct (based on what is in the issue).
I definitely seems to be a network issue, but my ip6 config seems fine
```
docker0   Link encap:Ethernet  HWaddr 02:42:39:c9:8d:62
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:39ff:fec9:8d62/64 Scope:Link

eth0      Link encap:Ethernet  HWaddr d4:3d:7e:4e:1f:1e
          inet addr:192.168.0.16  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::d63d:7eff:fe4e:1f1e/64 Scope:Link

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
```
I will try to use the image on another computer and/or find the network issue and give a feedback

**Comment by Guillaumebeuzeboc** [comment]
Ok I tried on a fresh install on another computer. And I have the exact same issue.

**Comment by PabloGN** [comment]
We should try with `latest` image. Also, I use hypriot OS Jessie.
